import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import TopNavbar from "@/app/TopNavbar/page";

// import TopNavbar from "@/app/TopNavbar/page";
import ProtectedRoute from "@/components/ProtectedRoute";
// import Navigation from "@/app/navigation/page";
// import Footer from "./Footer/page";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EchoSafe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProtectedRoute>
          {children}
          </ProtectedRoute>
         
      </body>
    </html>
  );
}
